---
name: "Build and release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: ["7", "focal"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Build for ${{ matrix.os }}"
        run: |
          export OS_VERSION=${{ matrix.os }}
          make package
      - name: "Upload package for passing to release job"
        uses: "actions/upload-artifact@v3"
        with:
          name: "pkg"
          path: "omnibus/pkg/*"
  release:
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Download packages from build job"
        uses: "actions/download-artifact@v3"
        with:
          name: "pkg"
      - name: "List packages"
        shell: "bash"
        run: |
          ls
      - name: "Release packages"
        uses: "softprops/action-gh-release@v1"
        with:
          generate_release_notes: true
          files: |
            *.rpm
            *.deb
...
